server:
  port: 8080
spring:
  application: framework

  http:
    encoding:
     charset: UTF-8
     enabled: true # Enable http encoding support.

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  datasource:
    # Druid连接池配置，官方配置参考：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.24.198.239/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: saya
    password: Saya.ac.cn.666
    driver-class-name: com.mysql.jdbc.Driver
    # Druid其他配置
    druid:
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
      min-idle: 10
      max-active: 20
      filters: stat,wall
      initial-size: 5
      max-wait: 10
      # Druid WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        url-pattern: /*
        enabled: true
      # Druid StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        allow:
        deny:
        url-pattern: /druid/*
        login-password: admin
        reset-enable: true
        login-username: admin
        enabled: true


  mail:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    username: 504804540@qq.com
    password: abfekqvcpsbrbhie
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.saya.framework.api.entity
  config-location: classpath:mybatis/config/mybatis-config.xml

rocketmq:
  ###producer
  producer:
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: my-group
    #mq的nameserver地址
    namesrvAddr: 120.132.116.155:9876
    instanceName: rmq-instance
    topic: demo-topic
    tag: demo-tag
    #发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    #消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096


  ###consumer
  consumer:
    groupName: my-group
    topic: demo-topic
    tag: demo-tag
    namesrvAddr: 120.132.116.155:9876
    consumeThreadMax: 64
    consumeThreadMin: 20
    animal:
      tag: saya
      topic: saya
